apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc-test
spec:
  storageClassName: linstor-ssd-lvmthin-r2
  dataSource:
    name: mypvc
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
