apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linstor-ssd-lvmthin-r2
  resources:
    requests:
      storage: 10Gi
