apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-recovered
spec:
  storageClassName: linstor-ssd-lvmthin-r2
  dataSource:
    name: mydb-backup1
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
